# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0002_auto_20171028_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_slug',
            new_name='slug',
        ),
    ]
